name = "PrintTypesTersely"
uuid = "41b232b1-0de0-4a65-aab4-126884588aaf"
authors = ["Matěj Račinský <matej.racinsky@avast.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
JsonGrinder = "d201646e-a9c0-11e8-1063-23b139159713"
Mill = "1d0525e4-8992-11e8-313c-e310e1f6ddea"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Mill", "JsonGrinder"]
